### PR TITLE
add request timeout

### PR DESCRIPTION
**Pull request by aolu11**
add the whole request cycle timeout feature.

From Go 1.3 http.Client support this.

### CODE REVIEW

**Comment by levigross** [comment]
Can you please gofmt the code and submit tests that cover this?

**Comment by aolu11** [comment]
@levigross sorry, I'll try

**Comment by levigross** [comment]
Thanks! Can you please rebase your Pull request so that I can easily merge it?

**Comment by aolu11** [comment]
Rebase done

**Comment by levigross** [comment]
@aolu11 I am still getting a merge conflict when I am trying to merge your branch. Can you rebase your branch off of the latest master?

```bash
$ git pull git://github.com/aolu11/grequests.git master
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From git://github.com/aolu11/grequests
 * branch            master     -> FETCH_HEAD
Auto-merging utils.go
Auto-merging request.go
CONFLICT (content): Merge conflict in request.go
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by aolu11** [comment]
Sorry... I'm not very good at git.. maybe I should make this an issue

**Comment by levigross** [comment]
I would like to merge your branch so that you would be counted as a contributor to GRequests. If not, I am merge the branch in by myself.

**Comment by aolu11** [comment]
@levigross That would not be a problem, plz just merge it, thanks for your kindness~

**Comment by levigross** [comment]
My pleasure, thanks for your contribution! Now we just need the tests to pass....

**Pull request closed without merging**
