### PR TITLE
Sessions

### PR DESCRIPTION
**Pull request by levigross**

### CODE REVIEW

**Comment by levigross** [comment]
@marcosinger I am considering getting rid of the `Async` methods – what are your thoughts around this?

**Comment by marcosinger** [comment]
@levigross what is the main reason?

**Comment by levigross** [comment]
I am not including them within the Session API and I feel that if people want to make use of concurrent requests – they can write them in a better fashion that we can provide.

**Comment by marcosinger** [comment]
I agree with you :+1:

**Pull request merged**
